services:
  gateway:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_R2DBC_URL=r2dbc:postgresql://gateway-postgresql:5432/gateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
    ports:
      - "8080:8081"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      gateway-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  gateway-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microserviceuser:
    image: microserviceuser
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microserviceuser-postgresql:5432/microserviceUser
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microserviceuser-postgresql:5432/microserviceUser
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8082/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microserviceuser-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microserviceuser-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceUser
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microservicegir:
    image: microservicegir
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microservicegir-postgresql:5432/microserviceGIR
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microservicegir-postgresql:5432/microserviceGIR
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8083/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microservicegir-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microservicegir-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceGIR
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microserviceenseignement:
    image: microserviceenseignement
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microserviceenseignement-postgresql:5432/microserviceEnseignement
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microserviceenseignement-postgresql:5432/microserviceEnseignement
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8084/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microserviceenseignement-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microserviceenseignement-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceEnseignement
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microserviceedt:
    image: microserviceedt
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microserviceedt-postgresql:5432/microserviceEDT
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microserviceedt-postgresql:5432/microserviceEDT
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8085/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microserviceedt-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microserviceedt-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceEDT
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microservicegrh:
    image: microservicegrh
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microservicegrh-postgresql:5432/microserviceGRH
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microservicegrh-postgresql:5432/microserviceGRH
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8086/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microservicegrh-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microservicegrh-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceGRH
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microserviceaua:
    image: microserviceaua
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microserviceaua-postgresql:5432/microserviceAUA
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microserviceaua-postgresql:5432/microserviceAUA
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8087/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microserviceaua-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microserviceaua-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceAUA
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microservicedeliberation:
    image: microservicedeliberation
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microservicedeliberation-postgresql:5432/microserviceDeliberation
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microservicedeliberation-postgresql:5432/microserviceDeliberation
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8088/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microservicedeliberation-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microservicedeliberation-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceDeliberation
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microservicegd:
    image: microservicegd
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microservicegd-postgresql:5432/microserviceGD
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microservicegd-postgresql:5432/microserviceGD
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8089/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microservicegd-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microservicegd-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceGD
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microserviceaclc:
    image: microserviceaclc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microserviceaclc-postgresql:5432/microserviceACLC
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microserviceaclc-postgresql:5432/microserviceACLC
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8090/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microserviceaclc-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microserviceaclc-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceACLC
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microserviceaide:
    image: microserviceaide
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microserviceaide-postgresql:5432/microserviceAide
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microserviceaide-postgresql:5432/microserviceAide
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8091/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microserviceaide-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microserviceaide-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceAide
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  microserviceged:
    image: microserviceged
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microserviceged-postgresql:5432/microserviceGED
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microserviceged-postgresql:5432/microserviceGED
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8092/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      microserviceged-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  microserviceged-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=microserviceGED
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10

  consul:
    image: docker.io/bitnami/consul:1.17.0
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
  consul-config-loader:
    image: jhipster/consul-config-loader:v0.4.1
    volumes:
      - ./central-server-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    command: "start-dev --import-realm"
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_HEALTH_ENABLED=true
    ports:
      - 9080:9080
      - 9443:9443
    healthcheck:
      test: "bash /opt/keycloak/health-check.sh"
      interval: 5s
      timeout: 5s
      retries: 20
