apiVersion: v1
kind: Service
metadata:
  name: microserviceuser
  namespace: sencookseur
  labels:
    app: microserviceuser
spec:
  selector:
    app: microserviceuser
  ports:
    - name: http
      port: 8082
