apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microservicegd-postgresql-pvc
  namespace: sencookseur
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: microservicegd-postgresql
  namespace: sencookseur
  labels:
    app: microservicegd-postgresql
type: Opaque
data:
  postgresql-password: ZTBjZTdkZWQ0ZjM1YTNmOTc5MjQwNGFhYmQ4ZmE5YzQwOGEyZThlYTc2OTZhMTIzMWNmNWVhNDAyZDNj
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicegd-postgresql
  namespace: sencookseur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicegd-postgresql
  template:
    metadata:
      labels:
        app: microservicegd-postgresql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: microservicegd-postgresql-pvc
      containers:
        - name: postgres
          image: postgres:16.1
          env:
            - name: POSTGRES_USER
              value: microserviceGD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservicegd-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: microservicegd-postgresql
  namespace: sencookseur
spec:
  selector:
    app: microservicegd-postgresql
  ports:
    - port: 5432
