apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microservicegir-postgresql-pvc
  namespace: sn-ugb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: microservicegir-postgresql
  namespace: sn-ugb
  labels:
    app: microservicegir-postgresql
type: Opaque
data:
  postgresql-password: MWYxOTI1MWVjMWY5NjBlY2U1OTc1YTk3OGJkZWYzZmI5Y2E0MDM1MWUyYjQyZjFlNmM2MjcwMGE1ZjQ5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicegir-postgresql
  namespace: sn-ugb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicegir-postgresql
  template:
    metadata:
      labels:
        app: microservicegir-postgresql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: microservicegir-postgresql-pvc
      containers:
        - name: postgres
          image: postgres:16.1
          env:
            - name: POSTGRES_USER
              value: microserviceGIR
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservicegir-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: microservicegir-postgresql
  namespace: sn-ugb
spec:
  selector:
    app: microservicegir-postgresql
  ports:
    - port: 5432
