apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: diabrail/gateway
      context: ../gateway
      jib: {}
    - image: diabrail/microserviceuser
      context: ../microserviceUser
      jib: {}
    - image: diabrail/microservicegir
      context: ../microserviceGIR
      jib: {}
    - image: diabrail/microserviceenseignement
      context: ../microserviceEnseignement
      jib: {}
    - image: diabrail/microserviceedt
      context: ../microserviceEDT
      jib: {}
    - image: diabrail/microservicegrh
      context: ../microserviceGRH
      jib: {}
    - image: diabrail/microserviceaua
      context: ../microserviceAUA
      jib: {}
    - image: diabrail/microservicedeliberation
      context: ../microserviceDeliberation
      jib: {}
    - image: diabrail/microservicegd
      context: ../microserviceGD
      jib: {}
    - image: diabrail/microserviceaclc
      context: ../microserviceACLC
      jib: {}
    - image: diabrail/microserviceaide
      context: ../microserviceAide
      jib: {}
    - image: diabrail/microserviceged
      context: ../microserviceGED
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
