apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microserviceaua-app
  namespace: sn-ugb
  labels:
    team: sn-ugb
spec:
  selector:
    matchLabels:
      app: microserviceaua
  endpoints:
    - port: web
      path: /prometheusMetrics
