apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservicegrh-app
  namespace: sn-ugb
  labels:
    team: sn-ugb
spec:
  selector:
    matchLabels:
      app: microservicegrh
  endpoints:
    - port: web
      path: /prometheusMetrics
